// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpsqmuopzxmkkykczxcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwc3FtdW9wenhta2t5a2N6eGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4Nzk4NDQsImV4cCI6MjA3MjQ1NTg0NH0.kd0s243CNIYBflh3gzNu1dm1k4m7gkO1-XrEZBTCx-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});